[build]
  publish = "build"
  command = "yarn build"
  base = "peanutapp"
  functions = "netlify/functions"  # Ensure there is no trailing slash

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


